augmentation:
  Crop:
    x_min: 0
    y_min: 0
    x_max: 255
    y_max_: 255
    p: 1
  Resize:
    height: 255
    width: 255
    p: 1
  RandomBrightnessContrast:
    brightness_limit: 0.18
    contrast_limit: 0.18
    p: 0.5
  RandomGamma:
    gamma_limit: !!python/tuple [95, 105]
    p: 0.5
  Rotate:
    limit: 120
    border_mode: 2
    p: 0.7
  HorizontalFlip:
    p: 0.8
  VerticalFlip:
    p: 0.8

model:
