artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  competition_name: data-science-bowl-2018
  train_dataset_filename: stage1_train.zip
  test_dataset_filename: stage1_test.zip

data_validation:
  root_dir: artifacts/data_validation
  train_dataset: artifacts/data_ingestion/train
  test_dataset: artifacts/data_ingestion/test
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/train
  train_path: artifacts/data_transformation/train
  validation_path: artifacts/data_transformation/validation
  test_path: artifacts/data_ingestion/test
  YAML_path: artifacts/data_transformation/dataset.yaml
  val_size: 0.2
  aug_size: 3

model_trainer:
  root_dir: artifacts/model_trainer
  model_names: [yolov8n-seg.pt, yolo11n-seg.pt]
  dataset_yaml: artifacts/data_transformation/dataset.yaml
